### ISSUE TITLE
Use packages installed by `rules_python_external`

### ISSUE THREAD

**Issue by dayfine** [dillon-giacoppo/rules_python_external#47] opened 2020-06-14 21:21 UTC
I have been using `rules_python_external` to build python targets, which has worked quite well. Recently I have this new case that I also want to use the packages installed directly. For example:

I am installing `notebook` to use the `jupyter` cli binary. I need `notebook` both in the build dependency and as a regular pip package to use the cli binary. If I only use `rules_python_external`, the latter is not available, as I found out `rules_python_external` put all packages under `/bazel-mypackage/external/py_deps`, which I suppose it's necessary for bazel discovery. As a result, right now I still need to `pip install notebook` in the virtual environment, which feels redundant.

Moreover, I think this actually prevent something from working: e.g. for jupyter, I need to enable some extensions from CLI, which are applied to the configs under `.venv/lib/python3.8/site-packages/`, but then when I run the bazel built binary, it does not know about the .venv config and doesn't work as expected (I think I can get working by putting the jupyter config under `/user/local/` but that doesn't feel very right.

Is there a recommended way for handling this?

**Comment by thundergolfer** [comment] 2020-06-15 00:43
I think the functionality you're after is this https://github.com/dillon-giacoppo/rules_python_external/pull/21

**Comment by thundergolfer** [comment] 2020-06-15 00:43
There's more detail about the problem in this issue as well: https://github.com/dillon-giacoppo/rules_python_external/issues/18

**Comment by dillon-giacoppo** [comment] 2020-08-16 09:16
Closing as a duplicate of #18 which as @thundergolfer mentioned should be solved with #21.

**Closed as completed by dillon-giacoppo** 2020-08-16 09:16 UTC
